version: '3.6'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
      - '28017:28017'
    volumes:
      - '/tmp:/data/db'
    environment:
      AUTH: 'no'
    hostname: mongo

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      - '5672:5672'
   
