server:
  port: 8080

spring:
  data:
    mongodb:
      database: coop

amqp:
  queue: voting-session-result-queue
  exchange: voting-session-result--exchange
  routingKey: voting-session-result-routingkey